# blender_manifest.toml

schema_version = "1.0.0"

id = "avatar_toolkit"
version = "0.1.0"
name = "Avatar Toolkit"
tagline = "A modern tool for importing and optimizing models for VRChat, Resonite, and other similar games."
maintainer = "Team NekoNeo"
type = "add-on"

blender_version_min = "4.3.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

wheels = [
  "lz4-4.3.3-cp311-cp311-macosx_11_0_arm64.whl",
  "lz4-4.3.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
  "lz4-4.3.3-cp311-cp311-win_amd64.whl"
]
